-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA AS D
WHERE D.PARENT_ID IN (SELECT E.ID FROM ECOLI_DATA AS E WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL))
ORDER BY ID ASC

/*
1. PARENT_ID가 NULL인 ID
2. 해당 ID를 PARENT_ID로 가지는 ID
*/