-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;

/*ITEM_INFO
ITEM_ID
ITEM_NAME
RARITY
PRICE

ITEM_TREE
ITEM_ID
PARENT_ITEM_ID(ROOT면 NULL)(PARENT_ITEM_ID->ITEM_ID로 업그레이드 가능)
*/