-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
UNION
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
/* ONLINE_SALE
ONLINE_SALE_ID : 온라인 상품 판매 아이디
USER_ID : 회원 아이디
PRODUCT_ID : 상품 아이디
SALES_AMOUT : 판매량
SALES_DATE : 판매일

OFFLINE_SALE
OFFLINE_SALE_ID : 오프라인 상품 판매 아이디
PRODUCT_ID : 상품 아이디
SALES_AMOUNT : 판매량
SALES_DATE : 판매일
*/