-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
WHERE ADDRESS REGEXP '^서울'
GROUP BY REST_ID
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC
/* REST_INFO
REST_ID : 아이디
REST_NAME : 이름
FOOD_TYPE : 음식 종류
VIEWS : 조회수
FAVORITES : 즐겨찾기 수
PACKING_LOG : 주차장 유무
ADDRESS : 주소
TEL : 전화 번호

REST_REVIEW
REVIEW_ID : 아이디
REST_ID : 식당 아이디
MEMBER_ID : 회원 아이디
REVIEW_SCORE : 점수
REVIEW_TEXT : 텍스트
REVIEW_DATE : 리뷰 작성일 */