-- 코드를 작성해주세요
SELECT COUNT(I.FISH_TYPE) AS FISH_COUNT, N.FISH_NAME
FROM FISH_NAME_INFO AS N JOIN FISH_INFO AS I USING(FISH_TYPE)
GROUP BY I.FISH_TYPE, N.FISH_NAME
ORDER BY FISH_COUNT DESC

/* FISH_INFO
ID : 아이디
FISH_TYPE : 물고기 종류
LENGTH : 길이(10이하 NULL)
TIME : 잡은 날짜

FISH_NAME_INFO
FISH_TYPE
FISH_NAME*/