-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, C.GENERATION+1
    FROM ECOLI_DATA AS E JOIN CTE AS C ON E.PARENT_ID=C.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM CTE
WHERE NOT EXISTS (SELECT 1 FROM ECOLI_DATA AS E WHERE E.PARENT_ID=CTE.ID)
GROUP BY GENERATION
ORDER BY GENERATION

/* ECOLI_DATA
ID : 개체 아이디
PARENT_ID : 부모 아이디(최초 NULL)
SIZE_OF_COLONY : 개체 크기
DIFFERENTIATION_DATE : 분화 날짜
GENOTYPE : 개체 형질*/