-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT T.ITEM_ID FROM ITEM_TREE AS T WHERE PARENT_ITEM_ID IN(SELECT I.ITEM_ID FROM ITEM_INFO AS I WHERE RARITY='RARE'))
ORDER BY ITEM_ID DESC;

/*1. RARITY='RARE'인 ITEM_ID
2. 해당 ITEM_ID를 가지고 있는 PARENT_ITEM_ID의 ITEM_ID
3. 해당 ITEM_ID의 I.ITEM_ID, ITEM_NAME, RARITY 출력*/