-- 코드를 작성해주세요
SELECT E.ID, E.GENOTYPE, D.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E JOIN ECOLI_DATA AS D ON D.ID=E.PARENT_ID
WHERE E.GENOTYPE & D.GENOTYPE = D.GENOTYPE
ORDER BY ID ASC;

/*1. GENOTYPE 2진수
2. PARENT_ID와 동일한 ID의 GENOTYPE 가지고 있나 GENOTYPE 가지고 있나
 ECOLI_DATA
ID : 아이디
PARENT_ID : 부모 아이디(최초는 NULL)
SIZE_OF_COLONY : 개체 크기
DEFFERENTIATION_DATE : 분화 날짜
GENOTYPE : 개체 형질
*/