-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM  SKILLCODES WHERE NAME='Python') =  (SELECT CODE FROM  SKILLCODES WHERE NAME='Python') OR  SKILL_CODE & (SELECT CODE FROM  SKILLCODES WHERE NAME='C#') = (SELECT CODE FROM  SKILLCODES WHERE NAME='C#')
ORDER BY ID;
/* SKILLCODES
NAME : 이름
CATEGORY : 범주
CODE : 코드 - 2 제곱수

DEVELOPERS
ID : 아이디
FIRST_NAME : 이름
LAST_NAME : 성
EMAIL : 이메일 
SKILL_CODE : 스킬 코드 - 2진수*/