-- 코드를 작성해주세요
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D JOIN SKILLCODES AS S ON S.CODE&D.SKILL_CODE=S.CODE
WHERE S.NAME='Python' OR S.NAME='C#'
ORDER BY ID;
/* SKILLCODES
NAME : 이름
CATEGORY : 범주
CODE : 코드 - 2 제곱수

DEVELOPERS
ID : 아이디
FIRST_NAME : 이름
LAST_NAME : 성
EMAIL : 이메일 
SKILL_CODE : 스킬 코드 - 2진수*/