-- 코드를 작성해주세요
SELECT YEAR(DATE_FORMAT(DIFFERENTIATION_DATE, '%Y-%m-%d')) AS YEAR, ((SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DATE_FORMAT(DIFFERENTIATION_DATE, '%Y-%m-%d'))=YEAR)-SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;