-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS FI JOIN FISH_NAME_INFO AS FNI USING(FISH_TYPE)
WHERE FNI.FISH_NAME='BASS' OR FNI.FISH_NAME='SNAPPER'
/*FISH_INFO
ID : 아이디
FISH_TYPE : 종류
LENGTH : 길이(10이하 NULL)
TIME : 잡은 날짜

FISH_NAME_INFO
FISH_TYPE : 종류
FISH_NAME : 이름*/