-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER>3000 AND EXISTS (SELECT 1 FROM ICECREAM_INFO WHERE INGREDIENT_TYPE='fruit_based' AND FIRST_HALF.FLAVOR=ICECREAM_INFO.FLAVOR)
ORDER BY TOTAL_ORDER DESC;