-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF JOIN ICECREAM_INFO USING(FLAVOR)
WHERE  TOTAL_ORDER>=3000 AND INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC;

/* FIRST_HALF
SHIPMENT_ID : 출하번호
FLAVOR : 맛(기본키)
TOTAL_ORDER : 총주문량

ICECREAM_INFO
FLAVOR : 맛(기본키.외래키)
INGREDIENT_TYPE : 성분 타입(sugar_based, fruit_based)*/
