-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS I JOIN FISH_NAME_INFO USING(FISH_TYPE)
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS L FROM FISH_INFO GROUP BY FISH_TYPE) AS F ON F.FISH_TYPE=I.FISH_TYPE AND F.L=I.LENGTH
ORDER BY ID

/* FISH_INFO WHERE FISH_TYPE,ID = (SELECT FISH_TYPE,ID FROM FISH_INFO GROUP BY FISH_TYPE HAVING MAX(LENGTH))
ID: 아이디
FISH_TYPE : 종류
LENGTH: 길이
TIME: 잡은 날짜

FISH_NAME_INFO
FISH_TYPE : 종류
FISH_NAME : 이름*/