-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF JOIN ICECREAM_INFO USING (FLAVOR)
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER

/*FIRST_HALF
SHIPMENT_ID : 출하번호
FLAVOR : 맛(기본키)
TOTAL_ORDER : 총주문량

ICECREAM_INFO
FLAVOR : 맛(기본키, 외래키)
INGREDIENT_TYPE : 성분타입(sugar_based, fruit_based)*/